# Generated by Django 4.2.7 on 2023-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(default='Новая', max_length=40, verbose_name='Статус')),
                ('date_of_completion', models.DateTimeField(verbose_name='Дата выполнения')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
