# Generated by Django 4.2.7 on 2023-12-15 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_task_title_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название типа')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_of_completion',
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(to='webapp.type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.status'),
        ),
    ]
