# Generated by Django 4.2.7 on 2024-01-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('edit_users_in_project', 'Может изменять пользователей в проекте')]},
        ),
    ]
